server:
  port: 8080
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/hanteo
      username: root
      password: Godnseo5548!@
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      connection-timeout: 30000
      max-lifetime: 30000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true